### ISSUE TITLE
ExpertSDR3 to be stopped in services before able to restart

### ISSUE THREAD

**Issue by ON4ASG** [VK6NX/EE-Software-TestLounge---documentation#3]
Hi,

Here each time I stop the Expert SDR3 software version 0.10.0 it looks like the software is stopped.
When startingup again, I get the warning: "There are other ExpertSDR3 instances running".
Then I must go to taskcontrol and stop background process.

After this it works ok.

Grts,
Hans
ON4ASG

**Comment by martin-dl9sad** [comment]
I have the sam problem !

Martin DL9SAD
